name: paginate_firestore_plus
description: A flutter package to simplify pagination with firestore data.
version: 1.0.3+4
homepage: https://github.com/sherazahmad720/paginate_firestore_plus
issue_tracker: https://github.com/sherazahmad720/paginate_firestore_plus/issues

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  cloud_firestore: ^6.0.0
  provider: ^6.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
